### ISSUE TITLE
database structure

### ISSUE THREAD

**Issue by t2t2** [cosmicradiotv/podcast-plugin#1]
**_Offtopic:**_ _I remember reading on either reddit or hackernews about some service that offers graphs that can be later editable and embedded in github issues (image). anyone remembers?_
- **Show**
  - id (autoincrement)
  - Name (string)
  - Slug (string)
  - Image (attached file)
- **Episode**
  - id (autoincrement)
  - title (string? might be short at 255 max)
  - show_id (show)
  - slug (string)
  - summary (text) - summary of what episode is about
  - content (text) - show notes, longer data
  - length (integer) - episode length (in seconds?)
  - release (datetime)
  - published (boolean)
  - Image (attached file) - optional, can cascade to show image
  - Tags (Tag, n:n)
  - Releases (Release, 1:n) - releases of an episode, one per format (eg. audio, video, youtube)
- **Release**
  - id (autoincrement)
  - episode_id (episode)
  - type (releasetype)
  - url (text)
  - size (bigint) - for filling the field in rss feeds
- **ReleaseType**
  - id (autoincrement)
  - type (string) - eg. audio/video/youtube/etc...., Used to generate the right player on page
  - filetype (string) - for audio/video, fills in rss feed
- **Tag**
  - id (autoincrement)
  - name (string)
  - slug (string)

**Comment by vincent404** [comment]
Might be good to have a length and potential SSL file link, though that might be something that can be done on the fly. Really the issue comes from a specific thing, so it might not be appropriate for the general plugin.  

Fun fact: for Twitter player cards, all things need to be ssl. 

-------Roberto J Villegas

**Comment by t2t2** [comment]
length: added

SSL: If it's a problem, then why not do everything https?

**Comment by vincent404** [comment]
Fair enough. Eh something to worry about more for the site itself versus the plugin, so consider it moot at this point. 

-------Roberto J Villegas

**Comment by t2t2** [comment]
do RSS feeds support protocol agnostic (//url) urls?

**Comment by vincent404** [comment]
Best practices state to include the full url. I'd say for full comparability with any situation to keep ssl as an optional thing. 

There's also the slew of things that iTunes need for their feeds, but that's probably best for another thread. 

-------Roberto J Villegas

**Comment by blendermf** [comment]
The only problem with always using https is that current crtv at least uses libsyn and podtrac. Podtrac does not support https from what I can tell(searching has given me nothing), and libsyn does support it, but not in any official way (there is zero documentation on it that I can find, and you have to modify links that you get returned after a redirect, and those links change, and may expire). Currently the site takes libsyn urls, follows the redirect and modifies the url to the correct domain for ssl, it's less than ideal. Obviously we can and should try to move away from that.

I'm currently looking through what I had while experimenting for database structure, and the features we discussed including to see what we may need to add. IDK if you've seen the features we've discussed, but I could share that doc if you want.

One thing was some kind of support for generalized categorization support (so things like our best of category, or the featured category can be supported easily, and those categories can be easily edited).  We'd want to include both querying those episodes network wide, and on a individual show basis. This was a thing we categorized not as a feature we need at launch, so actually this can wait. Same with things like social meta links.

As far as things we need, I think that has most things covered. Maybe a description for shows? We definitely use that.

As far as the episode/slug field, we at least on crtv end up using both, a slug for nice display in urls, and then the episode number for use in display on the site. Currently we don't have that auto incrementing, and it's also not unique (which was useful for retro fun time when we started doing shows with a sub title, like Indie is Magic). Auto-incrementing would work fine in that situation as long as it's not unique, and editable later. So that may be something we want to think about.

A way to support unpublished episodes might be nice as well, although maybe we could just use the release field (if it's past the release, it's published, then we have support for schedule posts). That's a little clunky though if you want something to stay unpublished for a while, and you don't know exactly when it will go up, you have to set a date arbitrarily later. Really by default it should be saved as unpublished when first created (unless specified otherwise), probably.

That's all I can think of for now.

**Comment by t2t2** [comment]
> One thing was some kind of support for generalized categorization support (so things like our best of category, or the featured category can be supported easily, and those categories can be easily edited). We'd want to include both querying those episodes network wide, and on a individual show basis. This was a thing we categorized not as a feature we need at launch, so actually this can wait. Same with things like social meta links.

Maybe a better name for this is tagging?

episode#/slug - probably better to just have it slug then, with default value of $show->episodes()->count() if left blank

Added published boolean

**Comment by blendermf** [comment]
yes, tagging for sure makes more sense

**Comment by blendermf** [comment]
also maybe a slugified version of the title for the default value of the slug? I think if we really need the number we can either get it, or store it separately. If the slug ends up being used for url that's far more useful especially if we migrate content over and want links to continue to work, and keep the format (although there's other ways around that if need be)

And I do realize this is meant to be general, so I mean maybe there could be a setting to choose what the default behaviour for that is (either the number or the slugified title)

**Comment by t2t2** [comment]
Hmm might leave it as configable thing, I personally prefer to have url as (<show>)/episode/<number>

**Comment by vincent404** [comment]
Big thing is to make sure the urls are meaningfully, if nothing more than for SEO and such. I'd probably say default to slugified title, but allow editing. 

-------Roberto J Villegas

**Comment by blendermf** [comment]
Yeah I completely understand both thought processes so making it configurable seems like it's the best option. It's not like it's a field that can't be edited, and we're just talking about the default value so it's not a big deal.
