### ISSUE TITLE
Episode component is broken

### ISSUE THREAD

**Issue by t2t2** [cosmicradiotv/podcast-plugin#21]
Broke in: 0afe3d0423030a115a525245f643425746a9effe

Page code

```
title = "{{episode.title}} - {{show.name}}"
url = "/show/:show_slug/episode/:episode_slug"
layout = "default"
hidden = "0"

[episode]
showSlug = "{{ :show_slug }}"
episodeSlug = "{{ :episode_slug }}"
updateTitle = "1"
==
<div class="container">
    {% component 'episode' %}
</div>
```

Output:

```
<div class="container">
    </div>
```

**Comment by blendermf** [comment]
Because of the shared episode partials, there is no longer a default partial for it, and you instead have to use the format {% partial "component_alias::episode" %} I realize this is not exactly ideal because you can't use the standard component markup. There may be a better way around this. I wonder if there is any way to modify what the component sees as the default partial.

**Comment by blendermf** [comment]
We could probably make a default.htm for each one and then reference the shared partial from there
